# Generated by Django 5.2 on 2025-04-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='제목', max_length=100)),
                ('content', models.TextField(help_text='내용')),
                ('music_link', models.CharField(blank=True, help_text='음악 링크', max_length=1024, null=True)),
                ('genre', models.CharField(help_text='장르', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
