# Generated by Django 5.2 on 2025-04-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='classification',
            field=models.CharField(default='자유게시판', help_text='분류', max_length=100),
        ),
    ]
