# Generated by Django 5.2 on 2025-05-21 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_postsummary'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer'),
        ),
    ]
